CREATE TABLE [dbo].[Assets]
(
	[Id] INT IDENTITY(1, 1) NOT NULL,
	[Symbol]    NVARCHAR(20) NOT NULL,     
	[Name]      NVARCHAR(100) NOT NULL,    

	[CreatedAt] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	[UpdatedAt] DATETIME2 NULL,
	[DeletedAt] DATETIME2 NULL,

	[IsActive] BIT NOT NULL DEFAULT 1,

	CONSTRAINT [PK_Assets] PRIMARY KEY CLUSTERED ([Id])
);

GO
CREATE UNIQUE INDEX [IXU_Assets_Symbol] ON [dbo].[Assets] ([Symbol]) WHERE [DeletedAt] IS NULL;
