CREATE TABLE [dbo].[Test]
(
	[Id]			INT IDENTITY(1,1)	NOT NULL ,
	[Name]			NVARCHAR(100)		NOT NULL,
	[CreatedAt]		DATETIME2			NOT NULL DEFAULT GETUTCDATE(),
	[UpdatedAt]		DATETIME2			NULL,
	[DeletedAt]		DATETIME2			NULL,
	[IsActive]		BIT					NOT NULL DEFAULT 1,
	CONSTRAINT [PK_Test] PRIMARY KEY CLUSTERED ([Id])
)
