// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CryptoPorfolio.Infrastructure.Entities;

public partial class Asset
{
    public int Id { get; set; }

    public string Symbol { get; set; } = null!;

    public string Name { get; set; } = null!;

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<UserAssetTransaction> UserAssetTransactions { get; set; } = new List<UserAssetTransaction>();

    public virtual ICollection<UserAsset> UserAssets { get; set; } = new List<UserAsset>();
}