// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CryptoPorfolio.Infrastructure.Entities;

public partial class UserAssetTransaction
{
    public long Id { get; set; }

    public int UserId { get; set; }

    public long UserAssetId { get; set; }

    public int AssetId { get; set; }

    public int CurrencyId { get; set; }

    public int TypeId { get; set; }

    public decimal Quantity { get; set; }

    public decimal Amount { get; set; }

    public decimal Price { get; set; }

    public DateTime ExecutedAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual Asset Asset { get; set; } = null!;

    public virtual Currency Currency { get; set; } = null!;

    public virtual TransactionType Type { get; set; } = null!;

    public virtual User User { get; set; } = null!;

    public virtual UserAsset UserAsset { get; set; } = null!;
}